site_name: Demo Docs
theme:
  name: material
  language: pl
  features:
    - navigation.tabs
nav:
  - Strona główna: index.md
  - Dokumentacja API: api.md
  - Instrukcja użytkownika: user-guide.md
extra:
  alternate:
    - name: Polski
      link: /
      lang: pl
    - name: English
      link: /en/
      lang: en
plugins:
  - search
